import { useMemo, useRef, useState } from 'react';
import { AccessibilityInfo, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View, findNodeHandle } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { AppIcon, ListRow } from '@/components/ui';
import { useTheme } from '@/providers/theme-provider';
import { radius, spacing } from '@/theme/tokens';

export type RelationOption = { description?: string | undefined; id: string; label: string };

export function RelationPickerField({ label, onChange, options, value }: { label: string; onChange: (value: string | null) => void; options: readonly RelationOption[]; value: string | null }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const { colors, reduceMotion } = useTheme(); const insets = useSafeAreaInsets(); const triggerRef = useRef<View>(null); const searchRef = useRef<TextInput>(null); const selected = options.find((item) => item.id === value);
  const filtered = useMemo(() => { const normalized = query.trim().toLocaleLowerCase(); return normalized ? options.filter((item) => `${item.label} ${item.description ?? ''}`.toLocaleLowerCase().includes(normalized)) : options; }, [options, query]);
  const focus = (target: View | TextInput | null) => { const node = findNodeHandle(target); if (node) AccessibilityInfo.setAccessibilityFocus(node); };
  const openPicker = () => { setQuery(''); setOpen(true); };
  const close = () => { setOpen(false); requestAnimationFrame(() => focus(triggerRef.current)); };
  const select = (next: string | null) => { onChange(next); close(); };
  return <><View style={styles.container}><Text style={[styles.label, { color: colors.text }]}>{label}</Text><Pressable accessibilityHint="Seçim listesini açar" accessibilityLabel={`${label}, ${selected?.label ?? 'seçilmedi'}`} accessibilityRole="button" onPress={openPicker} ref={triggerRef} style={({ pressed }) => [styles.field, { backgroundColor: colors.surfaceElevated, borderColor: colors.border }, pressed && { backgroundColor: colors.surfacePressed }]}><Text style={[styles.value, { color: selected ? colors.text : colors.textMuted }]}>{selected?.label ?? 'Seç'}</Text><AppIcon color={colors.textSubtle} name={{ ios: 'chevron.up.chevron.down', android: 'unfold_more' }} size={18} /></Pressable></View><Modal animationType={reduceMotion ? 'none' : 'slide'} onRequestClose={close} onShow={() => focus(searchRef.current)} transparent visible={open}><View style={styles.modal}><Pressable accessibilityLabel="Seçim listesini kapat" accessibilityRole="button" onPress={close} style={[StyleSheet.absoluteFill, { backgroundColor: colors.overlay }]} /><View accessibilityViewIsModal style={[styles.sheet, { backgroundColor: colors.surfaceElevated, paddingBottom: Math.max(insets.bottom, spacing.lg) }]}><View style={styles.heading}><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>{label}</Text><Pressable accessibilityLabel="Kapat" accessibilityRole="button" onPress={close} style={styles.close}><AppIcon color={colors.text} name={{ ios: 'xmark', android: 'close' }} /></Pressable></View><View style={[styles.search, { backgroundColor: colors.surfaceMuted, borderColor: colors.border }]}><AppIcon color={colors.textSubtle} name={{ ios: 'magnifyingglass', android: 'search' }} size={20} /><TextInput accessibilityLabel={`${label} seçeneklerinde ara`} autoCorrect={false} onChangeText={setQuery} placeholder="Ara" placeholderTextColor={colors.textSubtle} ref={searchRef} style={[styles.searchInput, { color: colors.text }]} value={query} /></View><ScrollView keyboardDismissMode="on-drag" keyboardShouldPersistTaps="handled"><ListRow icon={{ ios: 'xmark.circle', android: 'cancel' }} onPress={() => select(null)} title="Seçimi temizle" />{filtered.map((item) => <ListRow {...(item.description ? { description: item.description } : {})} icon={{ ios: item.id === value ? 'checkmark.circle.fill' : 'circle', android: item.id === value ? 'check_circle' : 'radio_button_unchecked' }} key={item.id} onPress={() => select(item.id)} title={item.label} />)}{filtered.length === 0 ? <Text accessibilityLiveRegion="polite" style={[styles.empty, { color: colors.textMuted }]}>Eşleşen seçenek bulunamadı.</Text> : null}</ScrollView></View></View></Modal></>;
}

const styles = StyleSheet.create({ close: { alignItems: 'center', height: 48, justifyContent: 'center', width: 48 }, container: { gap: spacing.sm }, empty: { padding: spacing.lg, textAlign: 'center' }, field: { alignItems: 'center', borderRadius: radius.lg, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', minHeight: 52, paddingHorizontal: spacing.md }, heading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, label: { fontSize: 14, fontWeight: '700' }, modal: { flex: 1, justifyContent: 'flex-end' }, search: { alignItems: 'center', borderRadius: radius.lg, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm, minHeight: 52, paddingHorizontal: spacing.md }, searchInput: { flex: 1, fontSize: 16, minHeight: 48 }, sheet: { borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, maxHeight: '82%', padding: spacing.lg }, title: { fontSize: 24, fontWeight: '900', marginBottom: spacing.md }, value: { flex: 1, fontSize: 16 } });
