import { useCallback, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { type Href, router, useFocusEffect } from 'expo-router';

import type { CalendarEvent, CalendarRangeResponse } from '@neta/api-contracts';

import { Badge, Button, Card, EmptyState, InfoBox, Screen, Skeleton } from '@/components/ui';
import { listCalendarEvents } from '@/features/calendar/api';
import { createVisibleMonthDays, createVisibleMonthRange, moveMonth, toDateKey, toLocalCalendarKey } from '@/features/calendar/date';
import { toClientError } from '@/lib/api/errors';
import { formatDateTime } from '@/lib/resource/format';
import { useSession } from '@/providers/session-provider';
import { useTheme } from '@/providers/theme-provider';
import { radius, spacing } from '@/theme/tokens';

type ViewMode = 'month' | 'agenda';
export default function CalendarScreen() {
  const { colors } = useTheme(); const session = useSession(); const locale = session.user?.preferences?.locale ?? session.instance?.defaultLocale ?? 'tr'; const timezone = session.user?.preferences?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone; const [mode, setMode] = useState<ViewMode>('month'); const [month, setMonth] = useState(new Date()); const [selected, setSelected] = useState(new Date()); const [data, setData] = useState<CalendarRangeResponse | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const requestRef = useRef(0); const range = useMemo(() => createVisibleMonthRange(month), [month]); const days = useMemo(() => createVisibleMonthDays(month), [month]);
  const load = useCallback(async () => { if (session.status !== 'authenticated' || session.role !== 'freelancer') return; const requestId = ++requestRef.current; setLoading(true); setError(null); try { const result = await listCalendarEvents(session.instance, session.user, { ...range, timezone }); if (requestId === requestRef.current) setData(result.data); } catch (loadError) { if (requestId === requestRef.current) setError(toClientError(loadError, 'Takvim alınamadı.').message); } finally { if (requestId === requestRef.current) setLoading(false); } }, [range, session, timezone]);
  useFocusEffect(useCallback(() => { void load(); return () => { requestRef.current += 1; }; }, [load]));
  const items = useMemo(() => data?.items ?? [], [data]); const selectedKey = toLocalCalendarKey(selected); const counts = useMemo(() => { const map = new Map<string, number>(); for (const event of items) { const key = toDateKey(event.startAt, timezone); map.set(key, (map.get(key) ?? 0) + 1); } return map; }, [items, timezone]); const visible = useMemo(() => mode === 'agenda' ? [...items].sort((a, b) => a.startAt.localeCompare(b.startAt)) : items.filter((item) => toDateKey(item.startAt, timezone) === selectedKey), [items, mode, selectedKey, timezone]);
  return <Screen onRefresh={() => void load()} refreshing={loading && data !== null} scroll><View style={styles.content}><View style={styles.heading}><View style={styles.copy}><Badge tone="primary">Takvim</Badge><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>Takvim ve agenda</Text><Text style={[styles.description, { color: colors.textMuted }]}>Toplantı, odak zamanı ve bağlı kayıtları zaman çizelgesinde gör.</Text></View><Button onPress={() => router.push('/calendar-event' as Href)}>Yeni etkinlik</Button></View><View accessibilityLabel="Takvim görünümü" accessibilityRole="radiogroup" style={styles.row}>{(['month', 'agenda'] as const).map((value) => <Choice key={value} label={value === 'month' ? 'Ay' : 'Agenda'} onPress={() => setMode(value)} selected={mode === value} />)}</View><Card style={styles.card}><View style={styles.monthHeader}><Button accessibilityLabel="Önceki ay" onPress={() => setMonth((value) => moveMonth(value, -1))} variant="ghost">Önceki</Button><Text accessibilityRole="header" style={[styles.sectionTitle, { color: colors.text }]}>{new Intl.DateTimeFormat(locale, { month: 'long', year: 'numeric' }).format(month)}</Text><Button accessibilityLabel="Sonraki ay" onPress={() => setMonth((value) => moveMonth(value, 1))} variant="ghost">Sonraki</Button></View>{mode === 'month' ? <ScrollView accessibilityLabel="Ay günleri" horizontal><View style={styles.grid}>{days.map((day) => { const key = toLocalCalendarKey(day); const active = key === selectedKey; const count = counts.get(key) ?? 0; return <Pressable accessibilityLabel={`${new Intl.DateTimeFormat(locale, { dateStyle: 'full' }).format(day)}, ${count} etkinlik`} accessibilityRole="radio" accessibilityState={{ checked: active }} key={key} onPress={() => setSelected(day)} style={[styles.day, active && { backgroundColor: colors.primary }]}><Text style={{ color: active ? colors.primaryForeground : colors.text }}>{day.getDate()}</Text>{count ? <Text style={{ color: active ? colors.primaryForeground : colors.primary }}>•</Text> : null}</Pressable>; })}</View></ScrollView> : null}</Card>{error ? <InfoBox action={<Button onPress={() => void load()} variant="ghost">Tekrar dene</Button>} description={error} title="Takvim yüklenemedi" tone="danger" /> : null}{loading && !data ? <Skeleton height={120} /> : null}<Text accessibilityRole="header" style={[styles.sectionTitle, { color: colors.text }]}>{mode === 'agenda' ? 'Altı haftalık agenda' : new Intl.DateTimeFormat(locale, { dateStyle: 'long' }).format(selected)}</Text>{!loading && data && visible.length === 0 ? <EmptyState action={<Button onPress={() => router.push('/calendar-event' as Href)}>Etkinlik ekle</Button>} description="Seçili aralıkta etkinlik bulunmuyor." title="Etkinlik yok" /> : null}{visible.map((event) => <EventCard event={event} key={event.id} locale={locale} />)}</View></Screen>;
}
function EventCard({ event, locale }: { event: CalendarEvent; locale: string }) { const { colors } = useTheme(); const content = <Card accessibilityLabel={`${event.title}, ${formatDateTime(event.startAt, locale)}`} style={styles.card}><View style={styles.row}><Text style={[styles.itemTitle, { color: colors.text }]}>{event.title}</Text><Badge tone={event.readOnly ? 'neutral' : 'primary'}>{event.source}</Badge></View><Text style={[styles.description, { color: colors.textMuted }]}>{formatDateTime(event.startAt, locale)} – {formatDateTime(event.endAt, locale)}</Text>{event.readOnly ? <Text style={[styles.caption, { color: colors.textSubtle }]}>Bağlı kayıttan gelir; salt okunurdur.</Text> : null}</Card>; if (event.readOnly) return content; return <Pressable accessibilityHint="Etkinlik detayını modal olarak açar" accessibilityRole="button" onPress={() => router.push(`/calendar-event?eventId=${encodeURIComponent(event.id)}` as Href)}>{content}</Pressable>; }
function Choice({ label, onPress, selected }: { label: string; onPress: () => void; selected: boolean }) { const { colors } = useTheme(); return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} onPress={onPress} style={[styles.choice, { backgroundColor: selected ? colors.primary : colors.surfaceMuted, borderColor: colors.border }]}><Text style={{ color: selected ? colors.primaryForeground : colors.text }}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ caption: { fontSize: 12 }, card: { gap: spacing.md }, choice: { borderRadius: radius.pill, borderWidth: StyleSheet.hairlineWidth, justifyContent: 'center', minHeight: 48, paddingHorizontal: spacing.md }, content: { gap: spacing.md, paddingVertical: spacing.xl }, copy: { flex: 1, gap: spacing.sm }, day: { alignItems: 'center', borderRadius: radius.md, height: 48, justifyContent: 'center', width: 48 }, description: { fontSize: 14, lineHeight: 21 }, grid: { flexDirection: 'row', flexWrap: 'wrap', width: 336 }, heading: { alignItems: 'flex-end', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, justifyContent: 'space-between' }, itemTitle: { flex: 1, fontSize: 17, fontWeight: '800' }, monthHeader: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' }, row: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, sectionTitle: { fontSize: 20, fontWeight: '900' }, title: { fontSize: 30, fontWeight: '900', letterSpacing: -0.6 } });
